[tool.poetry]
name = "cocobump"
version = "0.1.0"
description = "Manage changelog and bump project version number using conventional commits from latest git tag."
authors = ["Max Kovykov <kovykmax@gmail.com>", "Igor Davydenko <iam@igordavydenko.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/Luminaar/cocobump"
packages = [
  {include = "cocobump", from = "src"},
]
keywords = ["changelog", "conventional commit", "bump", "version", "calver", "semver", "pre release"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Environment :: Console",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development",
  "Topic :: Utilities",
  "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.6"
attrs = ">=20.2.0,<22"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
time-machine = "^2.3.1"

[tool.poetry.scripts]
badabump = "badabump.cli.app:main"
badabump-ci = "badabump.cli.ci_app:main"

[tool.black]
line_length = 79
target_version = ["py36"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
